easy_admin:
    design:
        menu:
            - { entity: Coupon, label: coupon.label, icon: usd, default: true }
            - { entity: Brand, label: brand.label, icon: id-badge }
            - { entity: BrandCategory, label: brand_category.label, icon: tag }
